# Generated by Django 6.0.2 on 2026-03-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_doctorprofile_contact_no_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
    ]
