# Generated by Django 6.0.2 on 2026-03-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_availability_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_held',
            field=models.BooleanField(default=False),
        ),
    ]
